refactor(dependency): pin snakeyaml dependency and remove jackson dependency.
Jackson dependencies were explicitly added during the monorepo changes to align with SnakeYAML version 1.31.
However, Spring Boot 3 requires SnakeYAML 1.33, so the version has been updated accordingly.
The previously added Jackson dependencies are no longer relevant and have been removed.

Below stacktrace for reference:

```
> Task :igor:igor-web:test

JenkinsServiceSpec > getProperties correctly deserializes properties} > com.netflix.spinnaker.igor.jenkins.service.JenkinsServiceSpec.getProperties correctly deserializes properties} [testCase: [extension:.yml, contents:
                    a: hello
                    b: world
                    c: 3
                    nested:
                        list:
                            - 1
                            - a
                , result:[a:hello, b:world, c:3, nested:[list:[1, a]]]], #2] FAILED
    Condition failed with Exception:

    service.getBuildProperties("PropertiesTest", genericBuild, "props$extension") == testCase.result
    |       |                                    |                    |
    |       |                                    |                    .yml
    |       |                                    GenericBuild(building=false, fullDisplayName=null, name=null, number=1, duration=null, timestamp=null, result=null, artifacts=null, testResults=null, url=null, id=null, genericGitRevisions=null, properties=null)
    |       java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
    |           at com.netflix.spinnaker.igor.jenkins.service.JenkinsService.getBuildProperties(JenkinsService.java:290)
    |           at com.netflix.spinnaker.igor.jenkins.service.JenkinsServiceSpec.getProperties correctly deserializes properties}(JenkinsServiceSpec.groovy:650)
    <com.netflix.spinnaker.igor.jenkins.service.JenkinsService@4260de0d objectMapper=com.fasterxml.jackson.databind.ObjectMapper@876686 serviceName=http://my.jenkins.net jenkinsClient=retrofit2.Retrofit$1@6e5b7446 csrf=false retrySupport=com.netflix.spinnaker.kork.core.RetrySupport@513ad29e permissions=Permissions(permissions={}) circuitBreaker=CircuitBreaker 'jenkins-http://my.jenkins.net'>
        at com.netflix.spinnaker.igor.jenkins.service.JenkinsServiceSpec.getProperties correctly deserializes properties}(JenkinsServiceSpec.groovy:650)

        Caused by:
        java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
            at com.netflix.spinnaker.igor.jenkins.service.JenkinsService.getBuildProperties(JenkinsService.java:290)
            ... 1 more

354 tests completed, 1 failed

> Task :igor:igor-web:test FAILED
```