fix: spring-test is needed for main code as well so using implementation instead of testImplementation.
Error:
```
/home/runner/work/spinnaker/spinnaker/halyard/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java:61: error: package org.springframework.test.util does not exist
import org.springframework.test.util.TestSocketUtils;
                                    ^
1 error
> Task :halyard:halyard-deploy:compileJava

> Task :halyard:halyard-deploy:compileJava FAILED

FAILURE: Build failed with an exception.
> Task :halyard:halyard-config:compileTestJava
```