refactor(dependency): upgrade wiremock as part of spring boot 3.x and spring cloud 2022.0.x upgrade
Upgrading wiremock dependency to 3.0.4 and updating its coordinates.
Wiremock [3.0.0](https://github.com/wiremock/wiremock/releases/tag/3.0.0) onwards 2 major breaking changes are introduced:
1. support for Java 17, dropping Java 8 support
2. Change the Maven repository groupID to org.wiremock
https://github.com/wiremock/wiremock/releases?page=3
3. Change Artifact IDs of wiremock-jre8 and wiremock-jre8-standalone to wiremock and wiremock-standalone

===============================================================================================

refactor(dependency): pin elasticsearch as part of spring boot upgrade to 3.x

With Spring boot 3.0, Elasticsearch’s high-level REST client has been removed.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#elasticsearch-clients-and-templates

Error:
```
Execution failed for task ':clouddriver-elasticsearch:compileGroovy'.
> Could not resolve all files for configuration ':clouddriver-elasticsearch:compileClasspath'.
   > Could not find org.elasticsearch:elasticsearch:.
     Required by:
         project :clouddriver-elasticsearch
```
So, pining the elasticsearch dependency as 8.5.3 in accordance to the client used by Spring boot 3.0.13.

===============================================================================================

refactor(dependency): upgrade grpcVersion to 1.63.0 with spring boot upgrade to 3.x

While upgrading the spring boot to 3.0.13 and spring cloud 2022.0.5, encountered the below error:
```
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/UserIPServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/ValidatorIPServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/HealthGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/LoadBalancerServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/ClusterMembershipServiceGrpc.java:11: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/TaskRelocationServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceAllocationArchiveServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/TaskManagementServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/TaskManagementArchiveServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceConsumptionServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/MachineServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/v4/ResourceAllocationServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/AgentManagementServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/JobManagementServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/SupervisorServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/AutoScalingServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/SchedulerServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
clouddriver/clouddriver-titus/build/generated/source/proto/main/grpc/com/netflix/titus/grpc/protogen/EvictionServiceGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
```
The root cause of the issue is use of javax annotations in generated classes. So, upgrading the grpc-java to 1.63.0.
https://github.com/grpc/grpc-java/pull/10927
https://github.com/grpc/grpc-java/releases/tag/v1.63.0

===============================================================================================

refactor(classname): update name of the class ElasticSearchRestHealthContributorAutoConfiguration to ElasticsearchRestHealthContributorAutoConfiguration with spring boot upgrade to 3.x

While upgrading the spring boot to 3.0.13 and spring cloud 2022.0.5, encountered the below error:
```
 clouddriver/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/Main.groovy: 27: unable to resolve class org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthContributorAutoConfiguration
  @ line 27, column 1.
    import org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthContributorAutoConfiguration
    ^
```
The root cause is the rename of class `ElasticSearchRestHealthContributorAutoConfiguration` to `ElasticsearchRestHealthContributorAutoConfiguration` in spring boot 3.0.
https://stackoverflow.com/questions/76774786/when-updating-to-springboot3-1-1-i-can-not-import-elasticsearchresthealthcon
https://github.com/spring-projects/spring-boot/commit/27a936e466d149e7d9e31d7fdbf3d6e3d5d52ec3#diff-02d5da5a17d8684660a73d36f62bfd086a9acda3174d510eae97d032a825e8ef