chore(swagger): Upgrade Swagger to 2.2.22 for Spring Boot 3.0.13 compatibility
As part of the Spring Boot 3 upgrade, Swagger tests were failing due to incompatibility with springdoc-openapi version 1.8.0.
Upgraded to 2.2.22, which is stable and compatible with Spring Boot 3.0.13.

Error:
```
SwaggerTest > swaggerUiIsPresent() FAILED
    java.lang.AssertionError: 1 expectation failed.
    Expected status code <200> but was <404>.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
```

Reference: https://springdoc.org/#migration-to-v2