fix(security): resolve AuthenticationCredentialsNotFoundException by ensuring SecurityContext is properly set
As part of springboot 3 upgrade, security is enabled by default so we need to disable it.
```
ERROR 100258 --- [    Test worker] c.n.s.k.w.e.GenericExceptionHandlers     : [user] Internal Server Error
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:350)
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:214)
```