fix(tests): Update graphite properties as the new structure introduced in Springboot 3.0.x
Error:

```
 c.c.metrics.graphite.GraphiteReporter    : Unable to report to Graphite

    java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:583) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:507) ~[na:na]
        at java.base/java.net.Socket.<init>(Socket.java:319) ~[na:na]
        at java.base/javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277) ~[na:na]
        at com.codahale.metrics.graphite.PickledGraphite.connect(PickledGraphite.java:185) ~[metrics-graphite-4.2.22.jar:4.2.22]
        at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:374) ~[metrics-graphite-4.2.22.jar:4.2.22]
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:277) ~[metrics-core-4.2.22.jar:4.2.22]
        at com.codahale.metrics.ScheduledReporter.lambda$start$0(ScheduledReporter.java:206) ~[metrics-core-4.2.22.jar:4.2.22]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

```

Reference:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#actuator-metrics-export-properties